apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-grafana
  namespace: grafana
spec:
  encryptedData:
    github_client_id: AgB/S3M0ynTwJMcS6iaDAYG4ztAVlFGV+R1bG/gLsSodAzfZCSTjueoiu+cgW8ZwAbjrDHyonCpG8QNgnX+NRW4O49NoIFZ4aT//t2rrKxui4HeMIlDD1581VpmDoC0x6awRuHGvSBNj7MgS7AfBS9/4hGeXzwJBr153Xrwh4rWkNPpo//yzT8G2+sN1Eyv9dUqTjdCksY9WsflcZJJ7ZnBgC/9R9YgpmZU4bl48N7W9pBmxVi9Wux8v8h5cFAm3byHMlLm16G68MyRBm7b8K2+bQK05IAl4lw9HXRstlzGLyXznteST5bwEj/ZOoqCL6LmpRmaiO5z7nFnnfWP737WOUCleO/805gg1/wMBNFy6O8wAysVCzKHiRsQD8coJ9f1RasjXGMnyPDoFFjFygsw+xydbrdC8p+tLCUxOhGA5LZr7UkDJ42SPfY+662DcYZTCIqssR24V8l11b1f3PZViHxNzh5FuefoS/oy4bGvJd58B9XgicRxS9AUccehPS0LZn6XvmstZkpGww0a6AKndTytJmge+Po5WvM802s+s81qq4UAVx/alq6S5NaC6+qb8jQq6c9A2q4CaiMjF1f4HssocAWbBM5sDNGi3p+XX8ceE2gPkmMTSymuVTauY63YhqtMgZfFTL0/Amvyw7X5RL4xJgKKnyfVuixu9hjoDm9T1kyWMlVfgq8gBtiZwry78OMwq8SFK/8nGsFTXaf0+mKM/RA==
    github_client_secret: AgBYzjn2GVPjTBnmi2sfl3XNh7L7wv1Cc3DodqDjEpB/fYS4WNMqilOnRkZfN+PsxmGhuTo+RPLgRfjNAk8H4XciQpOvv7yqZkwwQWKPcvmh50wXO7R7tmHcAmS5ruhaj/56B/dFKcWU93aDDelo6Q8CwK0otJxs34L4plRhstHtcCyCvpg5TuGnSp4FNtwQqy7lnh8HiKSXpGe+IgnZ+R3+TVnnNejXIh7TSvKzExTBaH0xYubxdp2eryQ2ZRzasQeptigaR8vZFazOwEBu/VEVXHMdrfUfUBmTFabM8E8drmvH/vOgjS5GJAPsdlDQj8Jkj0rW3RiaHhsaSYgK0pdJyyG1r/wesNm2VUakrs5OKHi+Lw54nDZ5A8xwzOm7IvLEx0V3maB3LB8qo4FeSwBwlSsqC3DziNZn4KyJzGZ5O6AFREQjz5Vo4B1IF2LGYwQIruEFMjOF1cFpZ+TGm0Cl18+UfJzvmuRwadWbvpGqYQ3+EFUcGHzpSS3UpCEWAdBoCDEbSLoP/i3wpHp8EiagcbcxW3T0BMgc91hqPDhdfmZ4Cpg4vHY8qNJ7+IjO4w1MWpkno0SojNQ8hfIg9P49aGAfPuqtmFLM+IKX5cZqrgaIs9iexayCoJdqOgg2xin9c4Zb7heR7tTVO+ryT0o7b4VF73EJROXI3zmka8JCckt4HCzOslfEKSml4eanF3qtWfRANIrhaxBA0l0uJuFYSiWdPQXdEnI5kA4ngsB6i3HbGmnJ1iAX
  template:
    metadata:
      creationTimestamp: null
      name: github-grafana
      namespace: grafana
    type: Opaque

