apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin
  namespace: terraform
spec:
  encryptedData:
    password: AgBZ64tjgqJvh/ac9pyGT98xUoh9LmU01phP61qBhQUThgG+SoWaiXc7QBkWy/WsXpmUB7lGbyQTcB7wQjqFO1L7ia6X66tU0zGkzx/yfbx4I4cg56FJl8sAehbK78qXU/llawRHUOYNiSLVG3elnQuiSjm6RBVX2MrvkVWAVgS9f659xVNAE/fV3A2w3ArMI4199stde4WMP7y/q3p0WVERVVB6oxXfTK17qsOuuC8WD7IQfAb79cTPCC7ie2sbTSxFVaJ7sR9dCFl6wXq5oWCcBZHmcG6+PlsnDqezV3c2/1csws84pftkVaByqxGJXsHjuFlA9Z3xxnCdhMrTg8l+mcHabxLMvGROKW3xWP1qpaIAzxLIWnE1y7ZlAXyvprzdtNfrxap7vEl1SUWfgDxxp+fNfX0NF7WBOigDgU0HabAE0GloiSy6/z9Mg89zfFx8bdHohYGLhjH7RCtR+q2rAs1FSu9Xq6Y6qFGm3OzT5P/1tzDJ8pJyQCgmD62qaPMRr6X7fQHqHj8xuVVKDpm70YKE1KVxz3j1utA8lL/vf2zkDkXox5/36HM6OKIyFtgk46DhbwEvSLKziD1Z5jyAd5O6NqYsTaVwZYDsxm1gpbhnRpafr8+ZB9iHMxHRREbTujcMzL5e8UOybszQBeaHa/3NMSPpzZJt7ZjRFpLCcbLNEF4CqkIzRyEduxmYNHUll4OOlZWmg7TodQoJXmQ7Cix8XBjwmfuwikU08LTN7A==
    username: AgAd+RR6NZQBRXFUbk2p5SCImSWOLizTFixJcP37fMC1PAriJvjdvCYsMmp5xN6PzeYvol7G64TZBLxAVS8twipVVddAsu/ostYr9uwdA/9JIv7yDPUpgw4Rbc/l2ioVfWIIjNDNgI1oTSqW628kcigBG89mutf2JoU2MPt+MkP65VkvvnvJcQfDxabrhZ6c8sgFyYWbVz4Fqj1uSabxa/piEHQcNgHaRMTUJF9gEadgEnvpE5IGfbFhsyFdiVTyfRJ+TKnJDl8g1+bMO8DKFb9v66oBgic0qc64oyZpFDKtLNrVmUXz8nIi9OYCRH7wmcXFz3/4hbI9wSE2+RJQE6zA9x/BDXSJ0Qoz165OI1JdtFdI2M8mRpiewrXpdkIeqcqwbZBI3M9Z5qRhQiZmCywTlOcmOTVA+8aJ6NFpUhB5nTpS+zRg4ppTYV4aAAoQoqUdqykYR66Vh/xB0iUl6ZsxFCTA/3M8t/6x6fFEjs/n9vhLQyLm496EAIpCCLUuWNPo3X8d3S7pJQkz4NvGx+Tp8vJM+zytGvNiQkli/vhzEEne3O+xDSxvlwCQqeUNrNzWatWxVnpJJTgTPOxEfBw+6xjwiCArL4iFoVMQ1GaTZiTmWrSAGZPnLhsCdZ5RhdEdMA3tZrWSbczvUR0jHs1X0giDgFNR2wyd8fKOcXA6xWbk/N4BbBKcCA+732GmplYkw/EnHA==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin
      namespace: terraform
    type: Opaque

