apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: terraformrc
  namespace: terraform
spec:
  encryptedData:
    credentials: AgCtJ3VdP9lc1PGML6ODuiR9/cmFJizvfl8uM9sPpH8XLogN/1JENYAxOS6Kt+WvVupd1xpi8wkvTHhaRrDwW+3Ce+dUvonlMc0iCMcrRMrZfZ2W1pFSPTZh5A3/bmaNc5wl3/q/VK8QvctRKIEiopqL37AMWZ+YP2rhWfSbL8oUd4YCvLWwqvlJTtgs0Pnni8O3EhTPOxGgXrZ0PcQqbjPeqcWZrZO/45RUirAO0iaiQSg8/Oxzmh3uCDtIOB/IKi9o+HBOaNUAnZ1vclzlpiO+xS/ytuf+k0aHnoKvhnS9JdJTi6Ut2GvzT2/DPf9pRjpsTc7h27RQ+My0FJLGB+78ktiuwP55ewPFacMNJKaMbHJPgIVjGQfdz8wBai6J0ygsVIAditkzfEPZTU1RCXeJhJ1iUJwsORB35uxpNfGGdskKFvqhg69I+e9RO3Z2uwnF8ACQnqgTT8dzSOj/bazjSerJUWwc80hhs1eDjFH02EJjhR+hPooLzbcVDA/tDkBnEMgWXBeUMkA/0Xq5604UxoAnXu2cCwGDAcLWTMdhFk4Rj1UOtQ9H3fFcbINsY4VTzhqswpitVR5VV1RER4fY8ID3wSbHAzo08mxTf8V12J/HRaAccxTHu8l1veN011/d0cGMAni0GoCURxto24yNIWG4fUHaprSznHe/kmg1th+h8ZW7G15cXI91Ct/9cqnIbY9mdXWLonzqkojRg+mjEGMn2WLgVrM8M/ofznkqzyqBBACeCmTWO/d8N5yZ3oiK6vZWiXwZnwuMVtys0kYVoV5eZgfnzFIfmCI9LKwBXsKWEBAs5Ab7trDLpxXJxfcFAMLIB7bFVbGm6qVdK9A3ZrLIbK0kGNUgzjkQhciAmg+LEIdZ
  template:
    metadata:
      creationTimestamp: null
      name: terraformrc
      namespace: terraform
    type: Opaque
