apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: terraformrc
  namespace: terraform
spec:
  encryptedData:
    credentials: AgCLP8/gXCJPEVsb4tkEGCzlQN9SqNRP7p1eyAaGqp/97EbR2a1kUCnZ3zQ+7kRKcP/aB7+jcGshgfXEOatm28AwmTj5c69b4s4pY+65mJFis1zDmaB2IgKAI/Tia5/Kbl51/dvq8s1h0rVuU4YZJxF/N8ptoczLMBDlRmzqVdAkm0zfqfEqmUsIwEULdELfxlFIDw0RdFHpcNDz4uV/p57lYS07s1vnVS9yhqv2D+/SwYqNuUk33Dh3uk0xOrC9BPXv5Piw/ez6HYTH7GUhit0+827R6KqDwh72tgVlKxE8w1MNUqBXdwIAmnukpc1F7ZZk9nHSiJhmSnbZ/6IgYJ44y0w9HzVMOv9sMIv393shXznkC0mcYxugMnORlQUC1x15MxX9gGlW5Ec34fcTUlhpYi6ycS5OB3AWaD6anfoGUIivOuzHdYGvwdm3FclydiM0z05BBIPR3On8/UgWxC1Kq12065eVZweOrAv6BjB24rqXg6eVQW9rEP7ve8fKNPFo9ozSepg38uXunMqmoLUm/ettsv68OM5leBqzt012oJZJDQzxVHeZh+fNO8yoNnwlkE8svWwaS0z3mKJrmaijGsvHz5o7jiw7KhB+aal6kgA5mGZNfjj9j2h/7DXQBOHWiSw3T92Y2bfY3xwvhowPIwTG2OUTWcXMEvK/YFuiNBnfwkQtts8YIGWJD8asNiAVs4yzgUBUSJWvjw8YFrXEgCr9G7V47PaUrJ2FQUQleyj5bcgttqDgCXvrmVh120piA7sq51Y8f4GqySCiDeybzhWdHZnrtGLBVxxvNa0csTBOh8H3eZi8DYs5mkc6/EkUSMgNVS4tANJovT63wXs1qMJYZTYM73aeIEi5SBYFw4yOFSmy
  template:
    metadata:
      creationTimestamp: null
      name: terraformrc
      namespace: terraform
    type: Opaque

